FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libjson-c-dev \
    libwebsockets-dev \
    libssl-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/tsl0922/ttyd.git /ttyd

WORKDIR /ttyd

RUN mkdir build && cd build && cmake .. && make && make install

EXPOSE 7681

CMD ["ttyd", "-p", "7681", "bash"]
